<template>
    <div
        class="
            w-screen
            h-screen
            flex
            items-center
            justify-center
            gap-x-4
            bg-gray-800
        "
    >
        <router-link
            to="alerts"
            class="
                bg-purple-700
                text-white
                rounded-lg
                shadow
                py-4
                px-6
                text-lg
                transform
                hover:translate-y-2
                transition-all
                duration-200
            "
            >Alerts</router-link
        >
        <router-link
            to="progress"
            class="
                bg-purple-700
                text-white
                rounded-lg
                shadow
                py-4
                px-6
                text-lg
                transform
                hover:translate-y-2
                transition-all
                duration-200
            "
            >Progress</router-link
        >
    </div>
</template>

<script>
export default {
    name: 'Home',
}
</script>
